import Link from "next/link";
import {requireProductAdmin} from "@/lib/productAdmin";
import {getSupabaseAdmin} from "@/lib/supabaseAdmin";
export const dynamic="force-dynamic";
type Filters={organization?:string;tenant?:string;days?:string;changed?:string;page?:string};
const PER_PAGE=50;
function url(f:Filters){const q=new URLSearchParams();Object.entries(f).forEach(([k,v])=>{if(v)q.set(k,v)});return `/admin/behavioral-learning?${q}`;}
export default async function Page({searchParams}:{searchParams:Promise<Filters>}){
 await requireProductAdmin();const f=await searchParams;const db=getSupabaseAdmin();
 const days=[7,30,90].includes(Number(f.days))?Number(f.days):30;
 const page=Math.max(1,Math.min(10000,parseInt(f.page||"1",10)||1));
 const since=new Date(Date.now()-days*86400000).toISOString();
 const [or,ms,gs]=await Promise.all([db.from("organizations").select("id,name").order("name"),db.from("microsoft_tenants").select("id,organization_id,tenant_name"),db.from("google_workspace_tenants").select("id,organization_id,display_name,primary_domain")]);
 const orgs=or.data||[];const organization=orgs.some(x=>x.id===f.organization)?f.organization||"":"";
 const tenants=[...(ms.data||[]).map(x=>({id:x.id,organization_id:x.organization_id,name:x.tenant_name||"Microsoft",provider:"Microsoft"})),...(gs.data||[]).map(x=>({id:x.id,organization_id:x.organization_id,name:x.display_name||x.primary_domain||"Google",provider:"Google"}))].filter(x=>!organization||x.organization_id===organization);
 const tenant=tenants.some(x=>x.id===f.tenant)?f.tenant||"":"";const changed=f.changed==="1";
 const base=(head=false)=>{let q=db.from("behavior_shadow_assessments").select("*",{count:"exact",head}).gte("event_time",since);if(organization)q=q.eq("organization_id",organization);if(tenant)q=q.eq("tenant_record_id",tenant);return q;};
 const [all,changedResult,records]=await Promise.all([base(true),base(true).neq("adjustment",0),changed?base().neq("adjustment",0).order("event_time",{ascending:false}).range((page-1)*PER_PAGE,page*PER_PAGE-1):base().order("event_time",{ascending:false}).range((page-1)*PER_PAGE,page*PER_PAGE-1)]);
 const error=all.error||changedResult.error||records.error;const total=all.count||0;const changedCount=changedResult.count||0;const filtered=changed?changedCount:total;const rows=records.data||[];
 const orgName=new Map(orgs.map(x=>[x.id,x.name||"Organization"]));const tenantName=new Map(tenants.map(x=>[x.id,x.name]));
 const query={organization,tenant,days:String(days),changed:changed?"1":""};
 return <><div className="adminBack"><Link href="/admin">← Product Admin</Link></div><div className="topbar"><div><div className="title">Behavioral Learning</div><div className="subtitle">Shadow mode · No impact on live risk scores, incidents or alerts</div></div></div>
 <div className="grid4 adminMetrics"><div className="card"><div className="label">Assessments · {days} days</div><div className="metric">{total.toLocaleString()}</div></div><div className="card"><div className="label">Proposed changes</div><div className="metric">{changedCount.toLocaleString()}</div></div><div className="card"><div className="label">Unchanged</div><div className="metric">{(total-changedCount).toLocaleString()}</div></div><div className="card"><div className="label">Changed share</div><div className="metric">{total?(100*changedCount/total).toFixed(1):"0.0"}%</div></div></div>
 <div className="section card"><div className="adminTableHeader"><div><h2>Shadow assessments</h2><div className="muted">UTC timestamps. A proposed adjustment does not necessarily mean improved accuracy.</div></div></div>
 <form method="get" action="/admin/behavioral-learning" className="learningFilters"><label>Period<select name="days" defaultValue={String(days)}><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option></select></label><label>Customer<select name="organization" defaultValue={organization}><option value="">All customers</option>{orgs.map(x=><option key={x.id} value={x.id}>{x.name||x.id}</option>)}</select></label><label>Tenant<select name="tenant" defaultValue={tenant}><option value="">All tenants</option>{tenants.map(x=><option key={x.id} value={x.id}>{x.name} ({x.provider})</option>)}</select></label><label>Changes<select name="changed" defaultValue={changed?"1":""}><option value="">All</option><option value="1">Changed only</option></select></label><button type="submit" className="btn">Apply</button></form>
 {error?<div className="adminComingSoon">Unable to load assessments: {error.message}. Verify the Phase 2B SQL migration.</div>:rows.length?<><div className="tableScroll"><table className="table learningTable"><thead><tr><th>Sign-in (UTC)</th><th>Customer / Tenant</th><th>User</th><th>Live</th><th>Proposed</th><th>Change</th><th>Evidence</th></tr></thead><tbody>{rows.map(r=><tr key={r.signin_id}><td>{new Date(r.event_time).toLocaleString("en-US",{timeZone:"UTC",timeZoneName:"short"})}</td><td>{orgName.get(r.organization_id)||"Unknown"}<div className="muted">{tenantName.get(r.tenant_record_id)||r.provider}</div></td><td className="learningUser">{r.user_principal_name}</td><td>{r.live_score}</td><td>{r.proposed_score}</td><td>{r.adjustment>0?"+":""}{r.adjustment}</td><td>{Array.isArray(r.reasons)&&r.reasons.length?r.reasons.join("; "):"No adjustment"}<div className="muted">Historical sign-ins: {r.history_count}</div></td></tr>)}</tbody></table></div><div className="learningPages"><span>Page {page} · {filtered.toLocaleString()} matching</span><div>{page>1&&<Link className="btn" href={url({...query,page:String(page-1)})}>Previous</Link>}{page*PER_PAGE<filtered&&<Link className="btn" href={url({...query,page:String(page+1)})}>Next</Link>}</div></div></>:<div className="empty">No assessments match these filters.</div>}</div><div className="adminComingSoon">Next validation step: compare shadow assessments with verified administrator outcomes and test threshold crossings before enabling any live score changes.</div></>;
}
